    // ................
	
	protected $middlewareGroups = [
        'web' => [
			// ...
            \App\Http\Middleware\TripWire::class
        ],
		// ...
    ];
	
	// ...............................